server {
    # Ouve na porta 80, que expusemos no Dockerfile
    listen 80;

    # Define a raiz onde os arquivos estáticos estão localizados
    root /usr/share/nginx/html;

    # A mágica para SPAs:
    # Tenta encontrar um arquivo correspondente à URL. Se não encontrar,
    # redireciona a requisição para o /index.html.
    location / {
        try_files $uri /index.html;
    }
}